version: '3.8'
services:
    webapp:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html/
        ports:
            - 8001:8000
        depends_on:
            - db
        networks:
            - rabbitmq-laravel
            - rabbitmq_go_net
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3321:3306
        networks:
            - rabbitmq-laravel

    phpmyadmin:
        image: phpmyadmin
        ports:
            - 9599:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            UPLOAD_LIMIT: 2G
        networks:
            - rabbitmq-laravel
networks:
    rabbitmq-laravel:
        external: true
    rabbitmq_go_net:
        external: true
