version: '3.8'
services:
  webapp:
    image: php:8.1.2-apache
    command: 'php ./artisan serve --host=0.0.0.0'
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - rabbitmq-laravel
      - rabbitmq_go_net
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'laravel'
      MYSQL_PASSWORD: 'pass'
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3320:3306
    networks:
      - rabbitmq-laravel

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9597:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 2G
    networks:
      - rabbitmq-laravel
networks:
  rabbitmq-laravel:
      external: true

  rabbitmq_go_net:
    external: true
